# -*- coding: utf-8 -*-
"""DecisionTree01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/100mP_mt_osiEt-anJI3CZ7pqVw9_E_Hv
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

#load data
file_path = "/content/cleaned_amazon_data (2).csv"
df = pd.read_csv(file_path)
print(df.columns)

# Feature Engineering: Extract features from product names
df['name_length'] = df['product_name'].astype(str).apply(len)

df['cleaned_product_name'] = df['product_name'].fillna("").str.lower().str.strip()

# TF-IDF Vectorization of product names
tfidf = TfidfVectorizer(max_features=1000, stop_words='english')
tfidf_features = tfidf.fit_transform(df['cleaned_product_name']).toarray()

# Combine TF-IDF features with other features
X = pd.concat([pd.DataFrame(tfidf_features), df[['name_length']]], axis=1)
# Convert all column names to strings
X.columns = X.columns.astype(str)
y = df['discounted_price']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Decision Tree Regressor
dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

# Evaluate Decision Tree Model
mae_dt = mean_absolute_error(y_test, y_pred_dt)
mse_dt = mean_squared_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print("Decision Tree Regressor:")
print(f"MAE: {mae_dt}, MSE: {mse_dt}, R²: {r2_dt}")

import matplotlib.pyplot as plt

plt.scatter(y_test, y_pred_dt)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')
plt.xlabel('Actual Prices')
plt.ylabel('Predicted Prices')
plt.title('Actual vs. Predicted Prices (Decision Tree)')
plt.show()

residuals = y_test - y_pred_dt
plt.scatter(y_pred_dt, residuals)
plt.axhline(y=0, color='red', linestyle='--')
plt.xlabel('Predicted Prices')
plt.ylabel('Residuals')
plt.title('Residual Plot (Decision Tree)')
plt.show()



