# -*- coding: utf-8 -*-
"""Exception Handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDE89R3AxZ9RWyJfDdQDNzZdid2QqQfh
"""

class InvalidProductData(Exception):
    pass

def validate_input(data_row):
    required = ['price', 'rating', 'category']
    for col in required:
        if pd.isnull(data_row.get(col)):
            raise InvalidProductData(f"Missing required field: {col}")
    return True