# -*- coding: utf-8 -*-
"""FE-Automatic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDE89R3AxZ9RWyJfDdQDNzZdid2QqQfh
"""

def log_feature_importance(model, feature_names):
    import pandas as pd
    fi = pd.Series(model.feature_importances_, index=feature_names).sort_values(ascending=False)
    print("Top 10 Important Features:\n", fi.head(10))