# -*- coding: utf-8 -*-
"""FE-TO-Class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDE89R3AxZ9RWyJfDdQDNzZdid2QqQfh
"""

class FeatureEngineer:
    def __init__(self, df):
        self.df = df.copy()

    def add_discount_percent(self):
        self.df['discount_percent'] = ((self.df['original_price'] - self.df['price']) / self.df['original_price']).round(2)
        return self

    def add_competitiveness_score(self):
        self.df['competitiveness'] = (self.df['price'] / self.df['competitor_avg_price']).round(2)
        return self

    def add_rating_to_price_ratio(self):
        self.df['rating_to_price'] = (self.df['rating'] / self.df['price']).fillna(0).round(2)
        return self

    def get_features(self):
        return self.df