# -*- coding: utf-8 -*-
"""Lable Encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_xGLwMN4xr-e2K5zR8JbsvP0lPduOP82
"""

# Reference: https://scikit-learn.org/stable/modules/preprocessing.html#encoding-categorical-features
# https://towardsdatascience.com/all-about-categorical-variable-encoding-305f3361fd02/

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load the dataset
df = pd.read_csv("/content/Feature_engineered_price_tracking_data.csv")

# Display initial info
print("Initial Data Overview:")
print(df.info())

# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns
print("\nCategorical columns:", list(categorical_cols))

# Apply Label Encoding to all categorical columns
label_encoded_df = df.copy()
le = LabelEncoder()

for col in categorical_cols:
    label_encoded_df[col] = le.fit_transform(label_encoded_df[col].astype(str))

print("\nLabel Encoded DataFrame (head):")
print(label_encoded_df.head())