# -*- coding: utf-8 -*-
"""LightGBM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDE89R3AxZ9RWyJfDdQDNzZdid2QqQfh
"""

import lightgbm as lgb

def train_lightgbm(X_train, y_train):
    model = lgb.LGBMRegressor(n_estimators=100, learning_rate=0.1)
    model.fit(X_train, y_train)
    return model