# -*- coding: utf-8 -*-
"""MissingValue-Logging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDE89R3AxZ9RWyJfDdQDNzZdid2QqQfh
"""

def clean_data(df):
    missing = df.isnull().sum()
    print(f"Missing data before cleaning:\n{missing[missing > 0]}")
    df = df.dropna(subset=['price', 'rating'])
    df['category'] = df['category'].fillna('Unknown')
    return df