# -*- coding: utf-8 -*-
"""ModelEval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDE89R3AxZ9RWyJfDdQDNzZdid2QqQfh
"""

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

def evaluate_model(y_true, y_pred):
    metrics = {
        'RMSE': mean_squared_error(y_true, y_pred, squared=False),
        'MAE': mean_absolute_error(y_true, y_pred),
        'R2': r2_score(y_true, y_pred)
    }
    return metrics