# -*- coding: utf-8 -*-
"""Pipeline-CrossValidation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDE89R3AxZ9RWyJfDdQDNzZdid2QqQfh
"""

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import RidgeCV

def build_pipeline():
    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('model', RidgeCV(alphas=[0.1, 1.0, 10.0]))
    ])
    return pipeline