# -*- coding: utf-8 -*-
"""SQLite Cache.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDE89R3AxZ9RWyJfDdQDNzZdid2QqQfh
"""

import sqlite3

def cache_product_data(df, db_path="product_cache.db"):
    with sqlite3.connect(db_path) as conn:
        df.to_sql("product_data", conn, if_exists="replace", index=False)