# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iAMOCNE6KoDPzdEhk99vZSTWTzVwl8I0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/pre-processed_data0302 (1).csv')
df

#Visualization 1: Bar Chart of Products by Main Category

df.groupby('main_category').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.gca().xaxis.grid(True, alpha=0.5)
plt.gca().yaxis.grid(False)
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.title("Main Category distribution")
plt.show()

#Visualization 2: Ratings vs Number of Reviews
df.plot(kind='scatter', x='ratings', y='no_of_ratings', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

#Visualization 3: Main category vs Ratings
figsize = (12, 1.2 * len(df['main_category'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='ratings', y='main_category', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

#Visulaization 4: Main category vs number of ratings
figsize = (10, 1.1 * len(df['main_category'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='no_of_ratings', y='main_category', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

#Visualization 5: Average discount by Main category
plt.figure(figsize=(6, 4))
df['discount_percentage'] = ((df['actual_price'] - df['discount_price']) / df['actual_price']) * 100
category_avg_discount = df.groupby("main_category")['discount_percentage'].mean().sort_values()
sns.barplot(x=category_avg_discount.index, y=category_avg_discount.values, palette="viridis")
plt.xticks(rotation=45, ha="right")
plt.title("Average Discount Percentage by Main Category")
plt.ylabel("Average Discount (%)")
plt.xlabel("Main Category")
plt.show()

#Visualization 6: Ratings Distribution
plt.figure(figsize=(8, 5))
sns.histplot(df['ratings'], bins=30, kde=True, color='green')
plt.title("Ratings Distribution")
plt.xlabel("Ratings")
plt.ylabel("Frequency")
plt.show()

#Visualization 7: Heatmap for Correlation
plt.figure(figsize=(8, 5))
corr = df[['actual_price', 'discount_price', 'ratings', 'no_of_ratings']].corr()
sns.heatmap(corr, annot=True, cmap="coolwarm", linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.show()