# -*- coding: utf-8 -*-
"""cron setup

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZczt7fGfL3iuWxHNz-dzFqNhRbnCRes
"""

# track_product_price.py
#chatgpt llm
#create and implement the cron job for my above code
#integrate timestamps for tracking
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def track_product_price(url, product_id):
    """Function to scrape price of a product from an eCommerce website."""
    headers = {'User-Agent': 'Mozilla/5.0'}
    response = requests.get(url, headers=headers)

    # Use BeautifulSoup to parse the HTML response and extract price (simplified example)
    soup = BeautifulSoup(response.content, 'html.parser')

    price = soup.find('span', {'class': 'price'}).text  # assuming the price is in a span with class 'price'

    # Save the product price along with timestamp for tracking
    timestamp = time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime())
    print(f"Product ID: {product_id} | Price: {price} | Timestamp: {timestamp}")

    # Save to a CSV or database for tracking
    tracking_data = pd.DataFrame([[product_id, price, timestamp]], columns=['product_id', 'price', 'timestamp'])
    tracking_data.to_csv(f'/path/to/my/price_tracking_{product_id}.csv', mode='a', header=False, index=False)

# Example usage:
if __name__ == "__main__":
    product_url = "https://www.amazon.in/s?bbn=81107433031&rh=n%3A81107433031%2Cp_85%3A10440599031&_encoding=UTF8&content-id=amzn1.sym.58c90a12-100b-4a2f-8e15-7c06f1abe2be&pd_rd_r=7dd4507c-ed06-4c09-862f-ef4ec45275ee&pd_rd_w=sJgSk&pd_rd_wg=FELAB&pf_rd_p=58c90a12-100b-4a2f-8e15-7c06f1abe2be&pf_rd_r=BNF7A5KJ3GESEPRWHQRV&ref=pd_hp_d_atf_unk"
    track_product_price(product_url, product_id=12345)