# -*- coding: utf-8 -*-
"""Data Dashboarding & Insights

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bn_B0ooWnGmkxvBQP5DRWCSB3znbmIsb
"""

!pip install -U kaleido # Install the kaleido package
import kaleido #Import the kaleido package so that plotly can use it
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from plotly.io import write_image

# Load dataset
df = pd.read_csv("/content/pre-processed_data0302.csv")

# Convert price columns to numeric
df['discount_price'] = pd.to_numeric(df['discount_price'], errors='coerce')
df['actual_price'] = pd.to_numeric(df['actual_price'], errors='coerce')
df['ratings'] = pd.to_numeric(df['ratings'], errors='coerce')
df['no_of_ratings'] = pd.to_numeric(df['no_of_ratings'], errors='coerce')

# Filter dataset
category = df['main_category'].unique()[0]  # Default category selection
filtered_df = df[df['main_category'] == category]

# Calculate discount percentage
filtered_df['discount_percentage'] = ((filtered_df['actual_price'] - filtered_df['discount_price']) / filtered_df['actual_price']) * 100

# Create subplots with improved spacing
dashboard = make_subplots(rows=4, cols=2, subplot_titles=(
    "Price Distribution", "Discount Percentage by Category",
    "Ratings vs Discount Price", "Top Rated Products",
    "Category-Wise Average Price", "Discount Price Histogram",
    "Price Fluctuation Over Time", "Review Count vs. Pricing"
), vertical_spacing=0.15)

# 1. Price Distribution
dashboard.add_trace(go.Histogram(x=filtered_df['actual_price'], name='Actual Price', opacity=0.6), row=1, col=1)
dashboard.add_trace(go.Histogram(x=filtered_df['discount_price'], name='Discount Price', opacity=0.6), row=1, col=1)

# 2. Discount Analysis
dashboard.add_trace(go.Box(y=filtered_df['discount_percentage'], name='Discount %'), row=1, col=2)

# 3. Ratings vs. Price Correlation
dashboard.add_trace(go.Scatter(x=filtered_df['ratings'], y=filtered_df['discount_price'], mode='markers', name='Ratings vs Price'), row=2, col=1)

# 4. Top Rated Products
top_rated = filtered_df.nlargest(10, 'ratings')
dashboard.add_trace(go.Bar(x=top_rated['name'], y=top_rated['ratings'], name='Top Rated'), row=2, col=2)

# 5. Category-Wise Average Price
avg_prices = df.groupby('main_category')[['actual_price', 'discount_price']].mean().reset_index()
dashboard.add_trace(go.Bar(x=avg_prices['main_category'], y=avg_prices['actual_price'], name='Actual Price'), row=3, col=1)
dashboard.add_trace(go.Bar(x=avg_prices['main_category'], y=avg_prices['discount_price'], name='Discount Price'), row=3, col=1)

# 6. Discount Price Histogram
dashboard.add_trace(go.Histogram(x=filtered_df['discount_price'], name='Discount Price Histogram', opacity=0.6), row=3, col=2)


# 8. Review Count vs. Pricing
dashboard.add_trace(go.Scatter(x=filtered_df['no_of_ratings'], y=filtered_df['discount_price'], mode='markers', name='Review Count vs Price'), row=4, col=2)

# Update layout with better spacing and sizing
dashboard.update_layout(height=1400, width=1600, title_text="Price Recommendation Dashboard", showlegend=True)


# Show dashboard
dashboard.show()