# -*- coding: utf-8 -*-
"""Elastic Search

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fdSD2hbweSpw-o7J-ScVVKIbWGnmzaj4
"""

import streamlit as st
from elasticsearch import Elasticsearch
#connect me to a elastic search
#Implement search query
#chatgpt llm

# Connect to Elasticsearch
es = Elasticsearch([{'host': 'localhost', 'port': 9200}])

# Function to search data from ElasticSearch
def search_articles(query):
    # Elasticsearch query to match the text in the content field
    body = {
        "query": {
            "match": {
                "content": query
            }
        }
    }
    # Perform the search
    res = es.search(index="articles", body=body)
    return res['hits']['hits']

# Streamlit UI for searching articles
st.title("ElasticSearch UI for Article Search")

# Get search query from user
query = st.text_input("Search for an article:")

if query:
    results = search_articles(query)

    if results:
        st.subheader("Search Results:")
        for result in results:
            st.write(f"**Title**: {result['_source']['title']}")
            st.write(f"**Author**: {result['_source']['author']}")
            st.write(f"**Content**: {result['_source']['content']}")
            st.write("---")
    else:
        st.write("No results found!")