# -*- coding: utf-8 -*-
"""Elastic Search Improv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fdSD2hbweSpw-o7J-ScVVKIbWGnmzaj4
"""

import streamlit as st
from elasticsearch import Elasticsearch
from datetime import datetime
#Implement fuzzy logic
#Pagination controls to be done
#Chatgptllm
# Connect to Elasticsearch
es = Elasticsearch([{'host': 'localhost', 'port': 9200}])

# Function to search electronics products from Elasticsearch
def search_products(query, page=1, size=10, filters=None):
    # Elasticsearch query to match the text in the product's title or description
    body = {
        "query": {
            "multi_match": {
                "query": query,
                "fields": ["title^2", "description", "brand^3"],  # Boosting title and brand fields
                "fuzziness": "AUTO"  # Allow for fuzzy search
            }
        },
        "from": (page - 1) * size,
        "size": size,
        "highlight": {
            "fields": {
                "description": {}  # Highlight product description
            }
        }
    }

    # Apply filters if provided
    if filters:
        body['query'] = {
            "bool": {
                "must": {
                    "multi_match": {
                        "query": query,
                        "fields": ["title^2", "description", "brand^3"]
                    }
                },
                "filter": filters
            }
        }

    # Perform the search
    res = es.search(index="electronics", body=body)
    return res['hits']

# Streamlit UI for searching electronics products
st.title("Electronics Product Search")

# Get search query from user
query = st.text_input("Search for electronics product:", "")

# Pagination settings
page = st.number_input("Page", min_value=1, max_value=100, value=1, step=1)

# Optional: Filter by price range, brand, etc.
filters = []
min_price = st.number_input("Min Price", min_value=0, value=0)
max_price = st.number_input("Max Price", min_value=0, value=5000)
if min_price and max_price:
    filters.append({"range": {"price": {"gte": min_price, "lte": max_price}}})

brand = st.text_input("Filter by Brand:")
if brand:
    filters.append({"term": {"brand": brand}})

# When query is provided, execute the search
if query:
    results = search_products(query, page, filters=filters)

    # Show total number of results
    st.write(f"**Total Results Found**: {results['total']['value']}")

    # Display the results
    if results['hits']:
        st.subheader("Search Results:")

        for result in results['hits']:
            st.write(f"**Product Name**: {result['_source']['title']}")
            st.write(f"**Brand**: {result['_source']['brand']}")
            st.write(f"**Price**: ${result['_source']['price']}")

            # Highlight matched terms in description
            description = result.get('highlight', {}).get('description', [result['_source']['description']])[0]
            st.write(f"**Description**: {description}")
            st.write(f"**Product Link**: [Link]({result['_source']['product_link']})")
            st.write("---")

        # Pagination Controls
        if page * 10 < results['total']['value']:
            if st.button("Next Page"):
                page += 1
                st.experimental_rerun()
        if page > 1:
            if st.button("Previous Page"):
                page -= 1
                st.experimental_rerun()

    else:
        st.write("No results found!")