# -*- coding: utf-8 -*-
"""FE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ybq1sW3nT2G-Eaet70cfVEHEWEysoECc
"""

import pandas as pd

from google.colab import files

uploaded = files.upload()

df = pd.read_csv('pre-processed_data2701.csv')
df.head()

# Check for missing values in ratings-related columns
print(df[['ratings', 'no_of_ratings']].isnull().sum())

import numpy as np

#popularity_score(Composite score combining ratings and number of ratings)
# Log transformation to handle skewness for large values
df['popularity_score'] = df['ratings'] * np.log1p(df['no_of_ratings'])

print(df[['ratings', 'no_of_ratings', 'popularity_score']].head())

# Bin ratings into categories: Low (0-3), Average (3-4), High (4-5)
df['rating_category'] = pd.cut(df['ratings'], bins=[0, 3, 4, 5], labels=['Low', 'Average', 'High'], include_lowest=True)

print(df[['ratings', 'rating_category']].value_counts())

#Discount Percentage Calculation
# Ensure no division by zero issues and handle missing values
df['discount_percentage'] = ((df['actual_price'] - df['discount_price']) / df['actual_price']).fillna(0)

# Clip negative values if any exist (usually due to missing or incorrect data)
df['discount_percentage'] = df['discount_percentage'].clip(lower=0)

# Categorizing prices into quantile-based buckets
df['price_bucket'] = pd.qcut(df['actual_price'], q=3, labels=['low', 'medium', 'high'])

# Visualize distribution of buckets
print(df['price_bucket'].value_counts())

# Simulating competitor prices by adding small random variations to actual prices
np.random.seed(42)
df['competitor_avg_price'] = df['actual_price'] * (1 + np.random.uniform(-0.1, 0.15, size=len(df)))

#Price Difference Calculation
df['price_difference'] = df['discount_price'] - df['competitor_avg_price']

# Competitiveness index (values < 1 indicate more competitive pricing)
df['competitiveness_index'] = (df['discount_price'] / df['competitor_avg_price']).fillna(1)

# Handling cases where competitor prices are zero or missing
df['competitiveness_index'] = df['competitiveness_index'].replace([np.inf, -np.inf], 1)

# Display relevant columns to inspect the transformations
columns_to_display = ['discount_percentage', 'price_bucket', 'competitor_avg_price', 'price_difference', 'competitiveness_index']
df[columns_to_display].head()