#OpenAI. (2025). ChatGPT (February 2025 Version). OpenAI. https://openai.com/

#first prompt : I Need keywords or score to relate the user input 
#last prompt : Adjust according to my column names


# -*- coding: utf-8 -*-
"""Features

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OMOx6TXBojkT2VZAYgyLBd7liXIpCno
"""

import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('/content/cleaned.csv')

# 1. Add 'discount_percentage' column
df['discount_percentage'] = ((df['actual_price'] - df['discounted_price']) / df['actual_price']) * 100
df['discount_percentage'] = df['discount_percentage'].fillna(0).clip(lower=0)

# 2. Add 'avg_price_category' column
df['avg_price_category'] = df.groupby('Category')['discounted_price'].transform('mean')

# 3. Add 'price_difference_category' column
df['price_difference_category'] = df['discounted_price'] - df['avg_price_category']



df.head()

# 5. Add 'is_high_discount' column
discount_threshold = 50  # Adjust this as needed
df['is_high_discount'] = (df['discount_percentage'] > discount_threshold).astype(int)




# Save the updated dataset
df.to_csv('1amazon_price_recommendation_features.csv', index=False)

print("Feature engineering for price recommendation completed!")
df.head()



from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# 1. Text Preprocessing: Clean product names (basic version)
df['cleaned_product_name'] = df['product_name'].str.lower().str.replace(r'\W', ' ', regex=True)

# Replace NaN values with an empty string in 'cleaned_product_name'
df['cleaned_product_name'] = df['cleaned_product_name'].fillna('')

# 2. Initialize TF-IDF Vectorizer
vectorizer = TfidfVectorizer(stop_words='english')

# 3. Fit TF-IDF on product names
tfidf_matrix = vectorizer.fit_transform(df['cleaned_product_name'])
# Function to get relevant products based on query
def get_relevant_products(query, top_n=5):
    # Preprocess the query
    query_cleaned = query.lower()

    # Convert query to TF-IDF vector
    query_tfidf = vectorizer.transform([query_cleaned])

    # Calculate cosine similarity between query and all product names
    similarity_scores = cosine_similarity(query_tfidf, tfidf_matrix).flatten()

    # Get top_n relevant products based on similarity scores
    top_indices = similarity_scores.argsort()[-top_n:][::-1]

    # Get the most relevant products
    relevant_products = df.iloc[top_indices]

    return relevant_products[['product_name', 'discounted_price', 'rating', 'Category', 'product_link', 'rating_count']]

# Example query to test relevance
query = "smartphone"
top_relevant_products = get_relevant_products(query, top_n=5)

# Display top relevant products
print(top_relevant_products)

df.to_csv('features.csv', index=False)
