# -*- coding: utf-8 -*-
"""Features

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OMOx6TXBojkT2VZAYgyLBd7liXIpCno
"""

import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('/content/cleaned.csv')

# 1. Add 'discount_percentage' column
df['discount_percentage'] = ((df['actual_price'] - df['discounted_price']) / df['actual_price']) * 100
df['discount_percentage'] = df['discount_percentage'].fillna(0).clip(lower=0)

# 2. Add 'avg_price_category' column
df['avg_price_category'] = df.groupby('Category')['discounted_price'].transform('mean')

# 3. Add 'price_difference_category' column
df['price_difference_category'] = df['discounted_price'] - df['avg_price_category']



df.head()

# 5. Add 'is_high_discount' column
discount_threshold = 50  # Adjust this as needed
df['is_high_discount'] = (df['discount_percentage'] > discount_threshold).astype(int)




# Save the updated dataset
df.to_csv('1amazon_price_recommendation_features.csv', index=False)

print("Feature engineering for price recommendation completed!")
df.head()

