# -*- coding: utf-8 -*-
"""KNN for Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xz-e6xlFYsALbjrWPULePxZdbPKLXv3K
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.impute import SimpleImputer

# Load dataset
df = pd.read_csv("/content/features.csv")
df

# Handle missing values
df.drop('product_name',axis=1)
df.drop('cleaned_product_name',axis=1)

# Assign the result back to df to actually drop columns
numeric_columns = df.select_dtypes(include=np.number).columns # Select only numeric columns for median calculation
df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].median()) # Fill missing values in numeric columns only

# Feature engineering: Calculate discount percentage
df['discount_percentage'] = (df['actual_price'] - df['discounted_price']) / df['actual_price']
#df.fillna(df.median(), inplace=True)

# Encode product names (if necessary)
le = LabelEncoder()
df['product_name_encoded'] = le.fit_transform(df['product_name'])

# Select features and target
features = ['actual_price', 'discounted_price', 'discount_percentage']
target = 'discounted_price'  # Predicting the best selling price

X = df[features]
y = df[target]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Impute missing values using the mean
imputer = SimpleImputer(strategy='mean') # Create an imputer instance
X_train = imputer.fit_transform(X_train) # Fit and transform on training data
X_test = imputer.transform(X_test) # Transform test data using the trained imputer

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train KNN model
knn = KNeighborsRegressor(n_neighbors=5, metric='euclidean')
knn.fit(X_train, y_train)

# Predict and evaluate
y_pred = knn.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"MAE: {mae}")
print(f"RMSE: {rmse}")

"""The model starts by loading libraries, dataset and handling missing values by filling them with the median. Then calculate the discount percentage to understand the relationship between the actual and discounted price. Since product names are text, they are converted into numerical values using label encoding. The selected features for prediction include actual_price, discounted_price, discount_percentage, and the encoded product name, while the target variable is discounted_price. The dataset is split into training and testing sets, with 80% used for training and 20% for testing. To enhance accuracy, numerical features are standardized. The K-Nearest Neighbors (KNN) regression model is then trained with k=5, meaning it finds the five most similar products to estimate the price. After training, the model predicts prices for test products and evaluates its performance. The final results show a Mean Absolute Error (MAE) of 34.171529366005444 and a Root Mean Squared Error (RMSE) of 583.7851190217981, indicating the average error in predictions. This approach helps sellers determine an optimal selling price based on past pricing patterns and discount strategies."""