# -*- coding: utf-8 -*-
"""Untitled88.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJq7-ZYcR6GBMCuYZ30SNz_kcU3-MCB5
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
#chatgpt llm
#first prompt implement best suitable mode
# Load raw data
data = pd.read_csv('/content/data.csv')

# Drop all non-numeric columns (including image/link/name etc.)
data = data.select_dtypes(include=[np.number]).dropna()

# Target: discount_price
X = data.drop('discount_price', axis=1)
y = data['discount_price']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

def evaluate_model(model, name):
    y_pred = model.predict(X_test)
    print(f"\n🔹 {name} Evaluation:")
    print(f"✅ RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.2f}")
    print(f"✅ MAE: {mean_absolute_error(y_test, y_pred):.2f}")
    print(f"✅ R²: {r2_score(y_test, y_pred):.2f}")

    from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
evaluate_model(model, "Linear Regression")

