# -*- coding: utf-8 -*-
"""model tune & ev

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VlbYtaQzRAlPjufOYyQTX9zCsgFtZ205
"""

# Importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
import joblib

#The LLM model used is based on GPT-4.
#first prompt: using the previously cleaned and featured data build a xgboost and rf model and evaluate them
#last prompt: save as pickle file and show a sample test case

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("\nTraining set size:", X_train.shape)
print("Test set size:", X_test.shape)

# Training Random Forest model
print("\nTraining Random Forest...")
rf = RandomForestRegressor(n_estimators=100, max_depth=10, min_samples_split=5, random_state=42)
rf.fit(X_train, y_train)

# Training XGBoost model
print("\nTraining XGBoost...")
xgb = XGBRegressor(objective='reg:squarederror', n_estimators=100, max_depth=5, learning_rate=0.1, random_state=42)
xgb.fit(X_train, y_train)

# Function to evaluate model performance
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)  # Predict on test data
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))  # Calculate RMSE
    mae = mean_absolute_error(y_test, y_pred)  # Calculate MAE
    r2 = r2_score(y_test, y_pred)  # Calculate R²
    print(f"RMSE: {rmse:.2f}")
    print(f"MAE: {mae:.2f}")
    print(f"R²: {r2:.2f}")

# Evaluate Random Forest model
print("\n📊 Random Forest Performance:")
evaluate_model(rf, X_test, y_test)

# Evaluate XGBoost model
print("\n📊 XGBoost Performance:")
evaluate_model(xgb, X_test, y_test)

# Defining parameter grid for Random Forest
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [5, 10, 20],
    'min_samples_split': [2, 5],
}

print("\nTuning Random Forest...")
# Using GridSearchCV for hyperparameter tuning
grid = GridSearchCV(RandomForestRegressor(), param_grid, cv=3, scoring='neg_mean_squared_error', verbose=1)
grid.fit(X_train, y_train)

print("\nBest Random Forest Parameters:", grid.best_params_)


best_rf = RandomForestRegressor(**grid.best_params_)  # Create model with best parameters
best_rf.fit(X_train, y_train)  # Train the model with the best parameters

# Save the best trained model to a file
joblib.dump(best_rf, 'best_rf_price_recommender.pkl')

# Make a prediction for a sample from the test set
sample = X_test.iloc[0]
predicted_price = best_rf.predict(sample.values.reshape(1, -1))
print("\nSample Prediction:")
print(f"Actual Price: {y_test.iloc[0]:.2f}, Predicted Price: {predicted_price[0]:.2f}")

print("\n✅ Price recommendation model built and saved successfully!")