# -*- coding: utf-8 -*-
"""Name features

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PoSIKC2QWi4IuLfLP4Bncd7ER14Rczep
"""

mport pandas as pd
from sklearn.preprocessing import LabelEncoder
from textblob import TextBlob

# Load dataset
df = pd.read_csv("/content/pre-processed_data2701.csv")

# --------- NAME FEATURE ENGINEERING ---------
df['name_word_count'] = df['name'].apply(lambda x: len(str(x).split()))
df['name_char_count'] = df['name'].apply(lambda x: len(str(x)))
df['name_sentiment'] = df['name'].apply(lambda x: TextBlob(str(x)).sentiment.polarity)

# --------- CATEGORY ENCODING ---------
label_encoder = LabelEncoder()
df['main_category_encoded'] = label_encoder.fit_transform(df['main_category'])
df['sub_category_encoded'] = label_encoder.fit_transform(df['sub_category'])

# Save processed data
df.to_csv("/content/processed_data_name_category.csv", index=False)
df.head()

df.head()