# -*- coding: utf-8 -*-
"""Ridge with hyper parameter and ev

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11CqooQs74p3p9YUGgpPr7tlj4rco-8jW
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Load raw data
data = pd.read_csv('/content/data.csv')

# Drop all non-numeric columns (including image/link/name etc.)
data = data.select_dtypes(include=[np.number]).dropna()

# Target: discount_price
X = data.drop('discount_price', axis=1)
y = data['discount_price']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

def evaluate_model(model, name):
    """Function to evaluate the model using RMSE, MAE, and R²"""
    y_pred = model.predict(X_test)
    print(f"\n🔹 {name} Evaluation:")
    print(f"✅ RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.2f}")
    print(f"✅ MAE: {mean_absolute_error(y_test, y_pred):.2f}")
    print(f"✅ R²: {r2_score(y_test, y_pred):.2f}")

# Ridge Regression with hyperparameter tuning
ridge_params = {'alpha': [0.01, 0.1, 1, 10, 100]}
ridge = Ridge()

# GridSearchCV for tuning alpha parameter
ridge_grid = GridSearchCV(ridge, ridge_params, cv=5, scoring='neg_mean_squared_error')
ridge_grid.fit(X_train, y_train)

# Get the best model from GridSearchCV
best_ridge = ridge_grid.best_estimator_

# Evaluate the best model
evaluate_model(best_ridge, "Ridge Regression (Tuned)")

# Print the best hyperparameters (alpha value)
print("\n✅ Best Ridge Model:")
print(best_ridge)
print(f"🔧 Best alpha: {ridge_grid.best_params_['alpha']}")

