# -*- coding: utf-8 -*-
"""SVR Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVELcwtljKZyqB9ZrAgqWd5mKcflC_kg
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

# Load the pre-processed data from the CSV file
data = pd.read_csv('/content/pre-processed_data0302.csv')

# Display the first few rows of the dataframe
print(data.head())

# Select relevant features and target variable for model building
features = ['ratings', 'no_of_ratings', 'discount_price', 'actual_price']
target = 'Price'

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data[features], data[target], test_size=0.2, random_state=42)

# Impute missing values in the target variable using the mean
y_train = y_train.fillna(y_train.mean())
y_test = y_test.fillna(y_test.mean())

# Initialize and train the Support Vector Regression (SVR) model
model = SVR(kernel='linear')
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate and print the mean squared error of the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# Print the model coefficients (weights)
print(f"Model Coefficients: {model.coef_}")

# Print the model intercept
print(f"Model Intercept: {model.intercept_}")