# -*- coding: utf-8 -*-
"""UI_Price_Recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UIY307-4-vnFnJEhHdY9_V6By18MDqpP
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
import joblib

# Load the pre-trained model (adjust the path if needed)
model = joblib.load('best_rf_price_recommender.pkl')

# Set page title and layout
st.set_page_config(page_title="Price Recommendation System", layout="wide")

# Sidebar navigation
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", ["Dashboard", "Product Search"])

# Load product data
@st.cache_data
def load_product_data():
    file_path = r"C:\Users\Diksha\Downloads\frauddet\frauddet\data.csv"  # Updated path
    try:
        data = pd.read_csv(file_path)
        return data
    except FileNotFoundError:
        st.error(f"File not found at {file_path}. Please check the file path.")
        return pd.DataFrame()

# Dashboard Page
if page == "Dashboard":
    st.title("Dashboard")
    st.markdown("""
        Welcome to the **Price Recommendation System Dashboard**!
        This page provides key insights and statistics about product recommendations.
    """)

    # Load and display product statistics
    df = load_product_data()
    if not df.empty:
        st.write("### Product Data")
        st.dataframe(df)

        # Product Rating Distribution
        st.write("### Product Rating Distribution")
        st.bar_chart(df["Rating"])

        # Average Discounted Price
        avg_price = df["Discounted Price"].mean()
        st.metric(label="Average Discounted Price", value=f"${avg_price:.2f}")

        # Total Number of Products
        total_products = df["Title"].nunique()
        st.metric(label="Total Products", value=total_products)

# Product Search Page
if page == "Product Search":
    st.title("Product Search")
    st.markdown("""
        Use the search bar below to find products and get price recommendations.
    """)

    # Load product data
    product_data = load_product_data()

    if not product_data.empty:
        # Search functionality based on 'Title'
        search_term = st.text_input("Search for a product", "")

        if search_term:
            filtered_products = product_data[product_data["Title"].str.contains(search_term, case=False, na=False)]

            if filtered_products.empty:
                st.write("No products found with that name.")
            else:
                st.write(f"Found {len(filtered_products)} products matching '{search_term}'")
                st.dataframe(filtered_products)

                # Select a product from the filtered results
                product_name = st.selectbox("Select a product", filtered_products["Title"])

                # Get the selected product's details
                selected_product = filtered_products[filtered_products["Title"] == product_name].iloc[0]

                st.write(f"### Product Details for **{product_name}**")
                st.write(f"**Brand**: {selected_product['Brand']}")
                st.write(f"**Rating**: {selected_product['Rating']}")
                st.write(f"**Discounted Price**: ${selected_product['Discounted Price']}")
                st.write(f"**Actual Price**: ${selected_product['Actual Price']}")
                st.write(f"**Stock Status**: {selected_product['Stock Status']}")
                st.write(f"**Review Count**: {selected_product['Review Count']}")
                st.write(f"**URL**: [Product Link]({selected_product['URL']})")

                # Prepare features for prediction
                encoder = LabelEncoder()
                scaler = MinMaxScaler()

                # Feature Engineering
                price_difference = selected_product["Actual Price"] - selected_product["Discounted Price"]
                discount_percentage = (price_difference / selected_product["Actual Price"]) * 100
                rating_scaled = scaler.fit_transform([[selected_product["Rating"]]])[0][0]
                brand_encoded = encoder.fit_transform([selected_product["Brand"]])[0]

                features = [
                    price_difference,
                    discount_percentage,
                    rating_scaled,
                    brand_encoded
                ]

                # Predict the discounted price
                def predict_price(model, features):
                    feature_values = np.array(features).reshape(1, -1)
                    predicted_price = model.predict(feature_values)
                    return predicted_price[0]

                predicted_price = predict_price(model, features)
                st.write(f"### Predicted Discounted Price: **${predicted_price:.2f}**")

                # Price Recommendation Status
                if predicted_price > selected_product["Discounted Price"]:
                    st.success("✅ This product is currently undervalued. Adjust your price")
                else:
                    st.warning("⚠️ This product might be overpriced. Review Once.")